### ISSUE TITLE
[BUG] Cannot compile on Ubuntu against lv2-dev 1.18.10

### ISSUE THREAD

**Issue by ghost** [Chowdhury-DSP/ChowMatrix#146]
**Describe the bug**
I'm trying to compile ChowMatrix on Ubuntu 23.04 with lv2-dev 1.18.10 but it doesn't compile

**To Reproduce**
1. follow install instructions
3. errors occur when running `cmake --build build --config Release`

**Expected behavior**
It should compile

**Screenshots**
Here's the terminal output

```
[ 90%] Building C object CMakeFiles/ChowMatrix_LV2_lv2_ttl_generator.dir/modules/JUCE/extras/Build/lv2_ttl_generator/lv2_ttl_generator.c.o
[ 90%] Linking C executable ChowMatrix_LV2_lv2_ttl_generator
[ 90%] Built target ChowMatrix_LV2_lv2_ttl_generator
[ 91%] Building CXX object CMakeFiles/ChowMatrix_LV2.dir/modules/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.cpp.o
[ 92%] Building CXX object CMakeFiles/ChowMatrix_LV2.dir/modules/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.o
In file included from /home/$USER/Desktop/ChowMatrix/modules/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp:27:
/home/$USER/Desktop/ChowMatrix/modules/JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:54:10: fatal error: lv2/lv2plug.in/ns/lv2core/lv2.h: No such file or directory
   54 | #include <lv2/lv2plug.in/ns/lv2core/lv2.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/ChowMatrix_LV2.dir/build.make:90: CMakeFiles/ChowMatrix_LV2.dir/modules/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:346: CMakeFiles/ChowMatrix_LV2.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 
**Additional context**
lv2-dev version 1.18.10-1kxstudio2

**Comment by jatinchowdhury18** [comment]
Hi there!

When we build ChowMatrix on Linux (Ubuntu 22.04) as part of our CI pipeline, we first install lv2-dev (see [here](https://github.com/Chowdhury-DSP/ChowMatrix/blob/main/.github/workflows/cmake.yml#L49)). I'm not familiar with the packages that are installed by default on kxstudio, but you may want to check that lv2-dev is installed on your system before building.

Other than that, it's a little bit tricky for me to provide much assistance for anything specific to kxstudio, aside from referring again to the Ubuntu CI build scripts and assuming that kxstudio will work more-or-less the same.

Thanks!
